server:
    port: 8080


spring:
#    db설정
    datasource:
        url: jdbc:mysql://localhost:3306/springboot3template
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: password

#    jpa 설정
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
                jdbc:
                    batch_size: 50

#   redis 설정
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}

jwt:
    secret:
        key: ${JWT_SECRET_KEY}